# AUTOGENERATED FROM nbs/07_visualization.ipynb - DO NOT EDIT
"""Plotting functions for validation results and confusion matrices."""

from __future__ import annotations
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
from typing import Optional, List, Dict, Any

from openness_classifier.validation import ValidationResult, ClassificationMetrics


FIGURE_STYLE = {
    'figure.figsize': (8, 6),
    'font.size': 12,
    'axes.titlesize': 14,
    'axes.labelsize': 12,
    'xtick.labelsize': 10,
    'ytick.labelsize': 10,
}

CATEGORY_ORDER = ['open', 'mostly_open', 'mostly_closed', 'closed']
CATEGORY_LABELS = ['Open', 'Mostly\nOpen', 'Mostly\nClosed', 'Closed']


def plot_confusion_matrix(
    confusion_matrix: np.ndarray,
    title: str = "Confusion Matrix",
    labels: Optional[List[str]] = None,
    normalize: bool = False,
    cmap: str = "Blues",
    figsize: tuple = (8, 6),
    save_path: Optional[str | Path] = None,
) -> plt.Figure:
    """Plot confusion matrix as heatmap."""
    if labels is None:
        labels = CATEGORY_LABELS

    if normalize:
        cm = confusion_matrix.astype('float') / confusion_matrix.sum(axis=1, keepdims=True)
        cm = np.nan_to_num(cm)
        fmt = '.2f'
    else:
        cm = confusion_matrix
        fmt = 'd'

    fig, ax = plt.subplots(figsize=figsize)

    sns.heatmap(
        cm,
        annot=True,
        fmt=fmt,
        cmap=cmap,
        xticklabels=labels,
        yticklabels=labels,
        ax=ax,
        cbar_kws={'label': 'Proportion' if normalize else 'Count'},
    )

    ax.set_xlabel('Predicted Label')
    ax.set_ylabel('True Label')
    ax.set_title(title)

    plt.tight_layout()

    if save_path:
        fig.savefig(save_path, dpi=300, bbox_inches='tight')

    return fig


def plot_validation_results(
    result: ValidationResult,
    save_dir: Optional[str | Path] = None,
) -> Dict[str, plt.Figure]:
    """Plot all visualizations for a validation result."""
    figures = {}

    if save_dir:
        save_dir = Path(save_dir)
        save_dir.mkdir(parents=True, exist_ok=True)

    if 'data' in result.confusion_matrices:
        fig = plot_confusion_matrix(
            result.confusion_matrices['data'],
            title='Data Availability Classification',
            save_path=save_dir / 'confusion_matrix_data.png' if save_dir else None,
        )
        figures['data_confusion'] = fig

        fig_norm = plot_confusion_matrix(
            result.confusion_matrices['data'],
            title='Data Availability Classification (Normalized)',
            normalize=True,
            save_path=save_dir / 'confusion_matrix_data_normalized.png' if save_dir else None,
        )
        figures['data_confusion_normalized'] = fig_norm

    if 'code' in result.confusion_matrices:
        fig = plot_confusion_matrix(
            result.confusion_matrices['code'],
            title='Code Availability Classification',
            save_path=save_dir / 'confusion_matrix_code.png' if save_dir else None,
        )
        figures['code_confusion'] = fig

    return figures


def plot_metrics_comparison(
    metrics_list: List[ClassificationMetrics],
    labels: List[str],
    title: str = "Model Comparison",
    figsize: tuple = (10, 6),
    save_path: Optional[str | Path] = None,
) -> plt.Figure:
    """Plot bar chart comparing metrics across models/runs."""
    fig, ax = plt.subplots(figsize=figsize)

    x = np.arange(len(labels))
    width = 0.2

    accuracies = [m.accuracy for m in metrics_list]
    kappas = [m.cohens_kappa for m in metrics_list]
    macro_f1s = [m.macro_f1 for m in metrics_list]

    ax.bar(x - width, accuracies, width, label='Accuracy', color='#2ecc71')
    ax.bar(x, kappas, width, label="Cohen's Kappa", color='#3498db')
    ax.bar(x + width, macro_f1s, width, label='Macro F1', color='#9b59b6')

    ax.set_xlabel('Model')
    ax.set_ylabel('Score')
    ax.set_title(title)
    ax.set_xticks(x)
    ax.set_xticklabels(labels)
    ax.legend()
    ax.set_ylim(0, 1)
    ax.axhline(y=0.8, color='gray', linestyle='--', alpha=0.5, label='Target (80%)')

    plt.tight_layout()

    if save_path:
        fig.savefig(save_path, dpi=300, bbox_inches='tight')

    return fig


def plot_class_distribution(
    distribution: Dict[str, int],
    title: str = "Training Data Distribution",
    figsize: tuple = (8, 5),
    save_path: Optional[str | Path] = None,
) -> plt.Figure:
    """Plot bar chart of class distribution."""
    fig, ax = plt.subplots(figsize=figsize)

    categories = [c for c in CATEGORY_ORDER if c in distribution]
    counts = [distribution[c] for c in categories]
    labels = [CATEGORY_LABELS[CATEGORY_ORDER.index(c)] for c in categories]

    colors = ['#27ae60', '#2ecc71', '#e74c3c', '#c0392b']

    bars = ax.bar(labels, counts, color=colors[:len(categories)])

    for bar, count in zip(bars, counts):
        ax.text(
            bar.get_x() + bar.get_width()/2,
            bar.get_height() + 0.5,
            str(count),
            ha='center',
            va='bottom',
            fontsize=10,
        )

    ax.set_xlabel('Openness Category')
    ax.set_ylabel('Count')
    ax.set_title(title)

    plt.tight_layout()

    if save_path:
        fig.savefig(save_path, dpi=300, bbox_inches='tight')

    return fig
